# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20161001_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
