# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Post Authors',
            },
        ),
        migrations.CreateModel(
            name='PostEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('height', models.IntegerField(default=400, null=True)),
                ('width', models.IntegerField(default=750, null=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='post_entry/', width_field='width')),
                ('views', models.IntegerField()),
                ('draft', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostAuthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'verbose_name_plural': 'Post Entries',
            },
        ),
    ]
