# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161001_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
