# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161001_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentry',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='postentry',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
