# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161002_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentry',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
