# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161012_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentry',
            name='last_update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
